version: "3.1"
services:
  mongodb:
    image: mongo:7.0.2-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: chat-app
    ports:
      - "27017:27017"
    volumes:
      - chat-app-dbdata:/data/db
    networks:
      - chat-app-network

volumes:
  chat-app-dbdata:

networks:
  chat-app-network:
    driver: bridge
